name: yml to json

on:
  push:
    paths:
      - 'providers.yml'
      - '.github/workflows/yml2json.yml'
  workflow_dispatch:

jobs:
  yml-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: generate yml from csv
        run: |
          python3 converters/yml2json.py
      - name: save changes
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "ğšŒğš›ğš˜ğš—ğš‹ğš˜ğš" || echo "no changes to commit"
          git push
